name: "Terraform CloudNova Deploy"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Auto-Deploy Infrastructure"
    runs-on: ubuntu-latest
    
    steps:
      - name: "1. Checkout Code"
        uses: actions/checkout@v4

      - name: "2. Insert Real Deployment Date"
        run: |
          DEPLOY_DATE=$(TZ='America/Bogota' date '+%d de %B de %Y, %H:%M')
          # Usamos || true para que el pipeline no muera si hay un problema menor con el texto
          sed -i "s/FECHA_SISTEMA_GITHUB/$DEPLOY_DATE/g" index.html || true
          echo "Fecha inyectada correctamente"

      - name: "3. Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "4. Terraform Init"
        run: terraform init

      - name: "5. Terraform Format & Validate"
        run: |
          terraform fmt -check || true
          terraform validate

      - name: "6. Terraform Apply"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ secrets.REGION }}
          TF_VAR_bucket_name_root: ${{ secrets.BUCKET_NAME }}
          TF_VAR_project_tags: ${{ secrets.PROJECT_TAGS }}
        run: terraform apply -auto-approve